import java.util.Random;
import java.util.Scanner;

public class Games {

    // PRE: accepts scanner from main
    // POST: asks the user for a 2 digit # & compares the
    // value to one generated by computer
    // evaluates whether the user 'won' the lottery

    public static void lotteryGame(Scanner input) {
        System.out.println("\nWELCOME TO THE LOTTERY!!\n");

        Random rand = new Random();

        int lottery = rand.nextInt(90) + 10;
        int lotteryDigit1 = lottery / 10;
        int lotteryDigit2 = lottery % 10;

        System.out.print("Enter a two-digit number: ");
        int userGuess = input.nextInt();
        input.nextLine(); // clear buffer

        while (userGuess < 10 || userGuess > 99) {
            System.out.print("Invalid input. Enter a two-digit number: ");
            userGuess = input.nextInt();
            input.nextLine(); // clear buffer
        }

        int guessDigit1 = userGuess / 10;
        int guessDigit2 = userGuess % 10;

        System.out.println("Lottery number was: " + lottery);

        if (userGuess == lottery) {
            System.out.println("Exact match! You win $10,000!");
        } else if (guessDigit1 == lotteryDigit2 && guessDigit2 == lotteryDigit1) {
            System.out.println("All digits match! You win $3,000!");
        } else if (guessDigit1 == lotteryDigit1 || guessDigit1 == lotteryDigit2 ||
                guessDigit2 == lotteryDigit1 || guessDigit2 == lotteryDigit2) {
            System.out.println("One digit matches! You win $1,000!");
        } else {
            System.out.println("Sorry, no match.");
        }
    }

    public static void playCraps(Scanner input) {
        System.out.println("\nWELCOME TO CRAPS!!\n");

        double netWorth = 50;
        Random rand = new Random();
        boolean playing = true;

        while (playing && netWorth > 0) {

            System.out.println("Current balance: $" + netWorth);
            System.out.print("Enter bet amount: ");
            double bet = input.nextDouble();
            input.nextLine(); // clear buffer

            while (bet <= 0 || bet > netWorth) {
                System.out.print("Invalid bet. Enter bet again: ");
                bet = input.nextDouble();
                input.nextLine(); // clear buffer
            }

            int sum = rollDice(rand);

            if (sum == 7 || sum == 11) {
                System.out.println("You win!");
                netWorth += bet;
            } else if (sum == 2 || sum == 3 || sum == 12) {
                System.out.println("You lose!");
                netWorth -= bet;
            } else {
                int point = sum;
                System.out.println("Point is set to: " + point);

                boolean rolling = true;
                while (rolling) {
                    sum = rollDice(rand);

                    if (sum == point) {
                        System.out.println("You win!");
                        netWorth += bet;
                        rolling = false;
                    } else if (sum == 7) {
                        System.out.println("You lose!");
                        netWorth -= bet;
                        rolling = false;
                    }
                }
            }

            if (netWorth <= 0) {
                System.out.println("You are out of money!");
                break;
            }

            System.out.print("Play again? (Y/N): ");
            String answer = input.nextLine();

            if (!answer.equalsIgnoreCase("Y")) {
                playing = false;
            }
        }

        System.out.println("Thanks for playing! You ended with $" + netWorth);
    }

    private static int rollDice(Random rand) {
        int die1 = rand.nextInt(6) + 1;
        int die2 = rand.nextInt(6) + 1;
        System.out.println("You rolled: " + die1 + " and " + die2);
        return die1 + die2;
    }

    public static void playScraps(Scanner input) {

        System.out.println("\nWELCOME TO SCRAPS!!\n");

        Random random = new Random();
        double worth = 50.00;
        boolean playing = true;

        while (playing && worth > 0) {

            System.out.println("Current balance: $" + worth);
            System.out.print("Enter bet amount: ");
            double bet = input.nextDouble();
            input.nextLine(); // clear buffer

            while (bet <= 0 || bet > worth) {
                System.out.print("Invalid bet. Enter bet again: ");
                bet = input.nextDouble();
                input.nextLine(); // clear buffer
            }

            int d1 = random.nextInt(8) + 1;
            int d2 = random.nextInt(8) + 1;
            int d3 = random.nextInt(8) + 1;

            int sum = d1 + d2 + d3;

            System.out.println("You rolled: " + d1 + ", " + d2 + ", " + d3);
            System.out.println("Total: " + sum);

            if (d1 == 8 || d2 == 8 || d3 == 8 ||
                    sum == 9 || sum == 10 || sum == 14) {
                System.out.println("You win!");
                worth += bet;
            } else if (d1 == 1 || d2 == 1 || d3 == 1 ||
                    sum == 8 || sum == 20 || sum == 23 || sum == 24) {
                System.out.println("You lose!");
                worth -= bet;
            } else {
                int point = sum;
                System.out.println("Point is set to: " + point);

                boolean rolling = true;
                while (rolling) {

                    d1 = random.nextInt(8) + 1;
                    d2 = random.nextInt(8) + 1;
                    d3 = random.nextInt(8) + 1;

                    sum = d1 + d2 + d3;

                    System.out.println("You rolled: " + d1 + ", " + d2 + ", " + d3);
                    System.out.println("Total: " + sum);

                    if (sum == point) {
                        System.out.println("You win!");
                        worth += bet;
                        rolling = false;
                    } else if (d1 == 8 || d2 == 8 || d3 == 8 || sum == 15) {
                        System.out.println("You lose!");
                        worth -= bet;
                        rolling = false;
                    }
                }
            }

            if (worth <= 0) {
                System.out.println("You are out of money!");
                break;
            }

            System.out.print("Play again? (Y/N): ");
            String answer = input.nextLine();

            if (!answer.equalsIgnoreCase("Y")) {
                playing = false;
            }
        }

        System.out.println("Thanks for playing! You ended with $" + worth);
    }

    public static void playRPS(Scanner input) {

        System.out.println("\nWELCOME TO ROCK PAPER SCISSORS!!\n");

        Random rand = new Random();

        System.out.println("0 - Rock");
        System.out.println("1 - Paper");
        System.out.println("2 - Scissors");

        int userChoice = input.nextInt();
        input.nextLine(); // clear buffer

        while (userChoice < 0 || userChoice > 2) {
            System.out.print("Invalid choice. Enter 0, 1, or 2: ");
            userChoice = input.nextInt();
            input.nextLine(); // clear buffer
        }

        int computerChoice = rand.nextInt(3);

        String[] options = { "Rock", "Paper", "Scissors" };

        System.out.println("You chose: " + options[userChoice]);
        System.out.println("Computer chose: " + options[computerChoice]);

        if (userChoice == computerChoice) {
            System.out.println("It's a tie!");
        } else if ((userChoice == 0 && computerChoice == 2) ||
                (userChoice == 1 && computerChoice == 0) ||
                (userChoice == 2 && computerChoice == 1)) {
            System.out.println("You win!");
        } else {
            System.out.println("You lose!");
        }
    }

    public static void playRPSSpock(Scanner input) {

        System.out.println("\nWELCOME TO ROCK PAPER SCISSORS SPOCK!!\n");

        Random rand = new Random();

        System.out.println("0 - Rock");
        System.out.println("1 - Paper");
        System.out.println("2 - Scissors");
        System.out.println("3 - Spock");

        int userChoice = input.nextInt();
        input.nextLine(); // clear buffer

        while (userChoice < 0 || userChoice > 3) {
            System.out.print("Invalid choice. Enter 0-3: ");
            userChoice = input.nextInt();
            input.nextLine(); // clear buffer
        }

        int computerChoice = rand.nextInt(4);

        String[] options = { "Rock", "Paper", "Scissors", "Spock" };

        System.out.println("You chose: " + options[userChoice]);
        System.out.println("Computer chose: " + options[computerChoice]);

        if (userChoice == computerChoice) {
            System.out.println("It's a tie!");
        } else if ((userChoice == 2 && computerChoice == 1) ||
                (userChoice == 1 && computerChoice == 0) ||
                (userChoice == 0 && computerChoice == 2) ||
                (userChoice == 1 && computerChoice == 3) ||
                (userChoice == 3 && computerChoice == 0) ||
                (userChoice == 3 && computerChoice == 2)) {
            System.out.println("You win!");
        } else {
            System.out.println("You lose!");
        }
    }
}